# Generated by Django 3.1.5 on 2021-01-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABC',
        ),
    ]
